// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blog.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type PostID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostID) Reset()         { *m = PostID{} }
func (m *PostID) String() string { return proto.CompactTextString(m) }
func (*PostID) ProtoMessage()    {}
func (*PostID) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{1}
}

func (m *PostID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostID.Unmarshal(m, b)
}
func (m *PostID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostID.Marshal(b, m, deterministic)
}
func (m *PostID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostID.Merge(m, src)
}
func (m *PostID) XXX_Size() int {
	return xxx_messageInfo_PostID.Size(m)
}
func (m *PostID) XXX_DiscardUnknown() {
	xxx_messageInfo_PostID.DiscardUnknown(m)
}

var xxx_messageInfo_PostID proto.InternalMessageInfo

func (m *PostID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PostResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{2}
}

func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *PostResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6745b25902462fb1, []int{3}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Post)(nil), "blog.Post")
	proto.RegisterType((*PostID)(nil), "blog.PostID")
	proto.RegisterType((*PostResponse)(nil), "blog.PostResponse")
	proto.RegisterType((*DeleteResponse)(nil), "blog.DeleteResponse")
}

func init() {
	proto.RegisterFile("blog.proto", fileDescriptor_6745b25902462fb1)
}

var fileDescriptor_6745b25902462fb1 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0x4c, 0x9b, 0xfa, 0x5a, 0x7a, 0x58, 0x7a, 0x58, 0x3c, 0x88, 0xe4, 0xe4, 0xa1,
	0x44, 0xa9, 0x7f, 0x40, 0x6a, 0x10, 0x7a, 0x93, 0x88, 0x17, 0x6f, 0x69, 0x32, 0x94, 0x85, 0x90,
	0x5d, 0x76, 0x47, 0xff, 0xa3, 0xff, 0x4a, 0x32, 0x21, 0x5a, 0xa5, 0x82, 0xb7, 0x7d, 0x33, 0x8f,
	0x6f, 0xde, 0x63, 0x81, 0x7d, 0x6b, 0x0f, 0xb9, 0xf3, 0x96, 0xad, 0x4a, 0xfa, 0x77, 0xf6, 0x88,
	0xe4, 0xc9, 0x06, 0x56, 0x4b, 0xc4, 0xa6, 0xd1, 0xd1, 0x55, 0x74, 0x7d, 0x5e, 0xc6, 0xa6, 0x51,
	0x2b, 0x4c, 0xd8, 0x70, 0x4b, 0x3a, 0x96, 0xd1, 0x20, 0x94, 0x46, 0x5a, 0xdb, 0x8e, 0xa9, 0x63,
	0x7d, 0x26, 0xf3, 0x51, 0x66, 0x1a, 0xd3, 0x9e, 0xb3, 0x2b, 0x7e, 0x93, 0xb2, 0x02, 0x8b, 0x7e,
	0x53, 0x52, 0x70, 0xb6, 0x0b, 0xa4, 0x2e, 0x91, 0x38, 0x1b, 0x58, 0x1c, 0xf3, 0x0d, 0x72, 0x89,
	0x24, 0x0e, 0x99, 0xf7, 0x97, 0xc9, 0x7b, 0xeb, 0xc7, 0xcb, 0x22, 0xb2, 0x7b, 0x2c, 0x0b, 0x6a,
	0x89, 0xe9, 0x8b, 0xa3, 0x91, 0x86, 0xb7, 0xba, 0xa6, 0x10, 0x04, 0x35, 0x2b, 0x47, 0x79, 0x9a,
	0xb0, 0xf9, 0x88, 0x30, 0xdf, 0xb6, 0xf6, 0xf0, 0x4c, 0xfe, 0xdd, 0xd4, 0xa4, 0xd6, 0xc0, 0x83,
	0xa7, 0x8a, 0x49, 0xfa, 0x1f, 0xe5, 0xb8, 0x50, 0x47, 0x99, 0xc6, 0x6b, 0x6b, 0xcc, 0x4a, 0xaa,
	0x1a, 0xf1, 0x2e, 0xbe, 0xf7, 0xbb, 0xe2, 0x0f, 0x37, 0x5e, 0x5c, 0xf3, 0x5f, 0xf6, 0x2d, 0x30,
	0x74, 0x3b, 0x41, 0x5f, 0x0d, 0xea, 0x67, 0xf7, 0x6d, 0xfa, 0x3a, 0xc9, 0x6f, 0x2a, 0x67, 0xf6,
	0x53, 0xf9, 0xcb, 0xbb, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x9e, 0xc0, 0xf2, 0xd9, 0x01,
	0x00, 0x00,
}
