// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blog.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PostResponse_Status int32

const (
	PostResponse_UNKNOWN PostResponse_Status = 0
	PostResponse_SUCCESS PostResponse_Status = 1
	PostResponse_ERROR   PostResponse_Status = 2
)

var PostResponse_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "ERROR",
}

var PostResponse_Status_value = map[string]int32{
	"UNKNOWN": 0,
	"SUCCESS": 1,
	"ERROR":   2,
}

func (x PostResponse_Status) String() string {
	return proto.EnumName(PostResponse_Status_name, int32(x))
}

func (PostResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{2, 0}
}

type DeleteResponse_Status int32

const (
	DeleteResponse_UNKNOWN DeleteResponse_Status = 0
	DeleteResponse_SUCCESS DeleteResponse_Status = 1
	DeleteResponse_ERROR   DeleteResponse_Status = 2
)

var DeleteResponse_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "ERROR",
}

var DeleteResponse_Status_value = map[string]int32{
	"UNKNOWN": 0,
	"SUCCESS": 1,
	"ERROR":   2,
}

func (x DeleteResponse_Status) String() string {
	return proto.EnumName(DeleteResponse_Status_name, int32(x))
}

func (DeleteResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{3, 0}
}

type Post struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	PublicationDate      string   `protobuf:"bytes,4,opt,name=publication_date,json=publicationDate,proto3" json:"publication_date,omitempty"`
	Tags                 []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Post) GetPublicationDate() string {
	if m != nil {
		return m.PublicationDate
	}
	return ""
}

func (m *Post) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type PostID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostID) Reset()         { *m = PostID{} }
func (m *PostID) String() string { return proto.CompactTextString(m) }
func (*PostID) ProtoMessage()    {}
func (*PostID) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{1}
}

func (m *PostID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostID.Unmarshal(m, b)
}
func (m *PostID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostID.Marshal(b, m, deterministic)
}
func (m *PostID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostID.Merge(m, src)
}
func (m *PostID) XXX_Size() int {
	return xxx_messageInfo_PostID.Size(m)
}
func (m *PostID) XXX_DiscardUnknown() {
	xxx_messageInfo_PostID.DiscardUnknown(m)
}

var xxx_messageInfo_PostID proto.InternalMessageInfo

func (m *PostID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PostResponse struct {
	Status               PostResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=blog.PostResponse_Status" json:"status,omitempty"`
	PostId               string              `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Post                 *Post               `protobuf:"bytes,3,opt,name=post,proto3" json:"post,omitempty"`
	Error                string              `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{2}
}

func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetStatus() PostResponse_Status {
	if m != nil {
		return m.Status
	}
	return PostResponse_UNKNOWN
}

func (m *PostResponse) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *PostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *PostResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteResponse struct {
	Status               DeleteResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=blog.DeleteResponse_Status" json:"status,omitempty"`
	Error                string                `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc5203cdc85000bc, []int{3}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetStatus() DeleteResponse_Status {
	if m != nil {
		return m.Status
	}
	return DeleteResponse_UNKNOWN
}

func (m *DeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("blog.PostResponse_Status", PostResponse_Status_name, PostResponse_Status_value)
	proto.RegisterEnum("blog.DeleteResponse_Status", DeleteResponse_Status_name, DeleteResponse_Status_value)
	proto.RegisterType((*Post)(nil), "blog.Post")
	proto.RegisterType((*PostID)(nil), "blog.PostID")
	proto.RegisterType((*PostResponse)(nil), "blog.PostResponse")
	proto.RegisterType((*DeleteResponse)(nil), "blog.DeleteResponse")
}

func init() {
	proto.RegisterFile("proto/blog.proto", fileDescriptor_fc5203cdc85000bc)
}

var fileDescriptor_fc5203cdc85000bc = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xdf, 0xaa, 0xda, 0x40,
	0x10, 0xc6, 0x9b, 0x98, 0x3f, 0x75, 0x14, 0x1b, 0x06, 0x69, 0xd3, 0x16, 0x8a, 0xe4, 0xca, 0x82,
	0x8d, 0xad, 0xbe, 0x81, 0xc6, 0x0b, 0x29, 0x68, 0xd9, 0x20, 0x85, 0xde, 0xc8, 0x6a, 0x16, 0xbb,
	0x10, 0xb2, 0x21, 0x19, 0xfb, 0x10, 0x85, 0x3e, 0x53, 0xaf, 0xfb, 0x56, 0x25, 0x9b, 0xd4, 0xe6,
	0x78, 0x3c, 0x70, 0x38, 0x77, 0xf3, 0xcd, 0x7c, 0xcc, 0xce, 0xef, 0x63, 0xc1, 0xcb, 0x0b, 0x45,
	0x6a, 0x7a, 0x48, 0xd5, 0x29, 0xd4, 0x25, 0x5a, 0x55, 0x1d, 0xfc, 0x32, 0xc0, 0xfa, 0xa2, 0x4a,
	0xc2, 0x21, 0xd8, 0x24, 0x29, 0x15, 0xbe, 0x31, 0x32, 0xc6, 0x5d, 0x56, 0x0b, 0xf4, 0xc1, 0x3d,
	0xaa, 0x8c, 0x44, 0x46, 0xbe, 0xa9, 0xfb, 0xff, 0x24, 0xbe, 0x04, 0x87, 0x9f, 0xe9, 0xbb, 0x2a,
	0xfc, 0x8e, 0x1e, 0x34, 0x0a, 0xdf, 0x83, 0x97, 0x9f, 0x0f, 0xa9, 0x3c, 0x72, 0x92, 0x2a, 0xdb,
	0x27, 0x9c, 0x84, 0x6f, 0x69, 0xc7, 0x8b, 0x56, 0x3f, 0xe2, 0x24, 0x10, 0xc1, 0x22, 0x7e, 0x2a,
	0x7d, 0x7b, 0xd4, 0x19, 0x77, 0x99, 0xae, 0x03, 0x1f, 0x9c, 0xea, 0x9c, 0x75, 0x84, 0x03, 0x30,
	0x65, 0xd2, 0x5c, 0x63, 0xca, 0x24, 0xf8, 0x6d, 0x40, 0xbf, 0x1a, 0x31, 0x51, 0xe6, 0x2a, 0x2b,
	0x05, 0x7e, 0x02, 0xa7, 0x24, 0x4e, 0xe7, 0x52, 0x9b, 0x06, 0xb3, 0xd7, 0xa1, 0xa6, 0x6b, 0x7b,
	0xc2, 0x58, 0x1b, 0x58, 0x63, 0xc4, 0x57, 0xe0, 0xe6, 0xaa, 0xa4, 0xbd, 0x4c, 0x1a, 0x1c, 0xa7,
	0x92, 0xeb, 0x04, 0xdf, 0x81, 0x55, 0x55, 0x9a, 0xa5, 0x37, 0x83, 0xd6, 0x26, 0xdd, 0xaf, 0xd2,
	0x11, 0x45, 0xa1, 0x8a, 0x06, 0xa5, 0x16, 0xc1, 0x07, 0x70, 0xea, 0x07, 0xb0, 0x07, 0xee, 0x6e,
	0xf3, 0x79, 0xb3, 0xfd, 0xba, 0xf1, 0x9e, 0x55, 0x22, 0xde, 0x2d, 0x97, 0xab, 0x38, 0xf6, 0x0c,
	0xec, 0x82, 0xbd, 0x62, 0x6c, 0xcb, 0x3c, 0x33, 0xf8, 0x69, 0xc0, 0x20, 0x12, 0xa9, 0x20, 0x71,
	0x61, 0x98, 0x5f, 0x31, 0xbc, 0xad, 0x5f, 0xbe, 0xeb, 0xba, 0xa6, 0xb8, 0x1c, 0x63, 0x3e, 0xfd,
	0x98, 0xd9, 0x1f, 0x03, 0x7a, 0x8b, 0x54, 0x9d, 0x62, 0x51, 0xfc, 0x90, 0x47, 0x81, 0x13, 0x80,
	0x65, 0x21, 0x38, 0x09, 0xfd, 0x1b, 0x5a, 0x09, 0xbc, 0xc1, 0xfb, 0xb9, 0xe2, 0x04, 0x9e, 0x33,
	0xc1, 0x13, 0xed, 0xed, 0xff, 0x9f, 0xaf, 0xa3, 0x07, 0xdc, 0xb0, 0xcb, 0x93, 0xc7, 0xee, 0xfe,
	0x08, 0x50, 0xf3, 0xdf, 0xd8, 0x3e, 0xbc, 0x95, 0xcf, 0xc2, 0xfd, 0x66, 0x87, 0x53, 0x9e, 0xcb,
	0x83, 0xa3, 0xbf, 0xf6, 0xfc, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0xff, 0x99, 0xc3, 0xee,
	0x02, 0x00, 0x00,
}
